"""Development-mode end-to-end graph smoke test."""
from __future__ import annotations

from datetime import datetime

from app.graph import build_graph


def test_full_graph_development_smoke(monkeypatch):
    monkeypatch.setattr("app.agents.planner.is_development", lambda: True)
    monkeypatch.setattr("app.agents.researcher.is_development", lambda: True)
    monkeypatch.setattr("app.agents.synthesizer.is_development", lambda: True)
    monkeypatch.setattr("app.agents.critic.is_development", lambda: True)

    graph = build_graph()
    session_id = "dev_smoke"
    state = {
        "user_query": "small development smoke query",
        "session_id": session_id,
        "started_at": datetime.now(),
        "plan": [],
        "current_iteration": 0,
        "max_iterations": 3,
        "gap_rounds": 0,
        "findings": [],
        "source_candidates": [],
        "draft_report": "",
        "critiques": [],
        "final_report": "",
        "citations": [],
        "quality_status": "unverified",
        "quality_warnings": [],
        "run_summary_path": "",
        "total_tool_calls": 0,
        "total_tokens_used": 0,
        "errors": [],
    }
    final = graph.invoke(state, config={"configurable": {"thread_id": session_id}})
    assert final.get("final_report")
    assert "Generated by autonomous-researcher" in final["final_report"]
    assert "quality=" in final["final_report"]
    assert not [e for e in final.get("errors", []) if "critic/provider failure" in e]
