"""System-level runnable smoke tests."""
from __future__ import annotations

import pytest

from app.graph import reset_graph
from main import _run


@pytest.mark.asyncio
async def test_cli_run_development_smoke(monkeypatch):
    """Exercise the same async path used by the CLI without external providers."""
    reset_graph()
    monkeypatch.setattr("main.is_development", lambda: True)
    monkeypatch.setattr("app.agents.planner.is_development", lambda: True)
    monkeypatch.setattr("app.agents.source_broker.is_development", lambda: True)
    monkeypatch.setattr("app.agents.researcher.is_development", lambda: True)
    monkeypatch.setattr("app.agents.synthesizer.is_development", lambda: True)
    monkeypatch.setattr("app.agents.critic.is_development", lambda: True)

    final = await _run(
        "small runnable smoke query",
        session_id="system_runnable_smoke",
        stream=False,
        use_memory=False,
    )

    assert final["final_report"]
    assert "Generated by autonomous-researcher" in final["final_report"]
    assert final["current_iteration"] >= 1
    assert final["quality_status"] in {"verified", "partial", "unverified"}
    assert not [e for e in final.get("errors", []) if "provider failure" in e]
    reset_graph()
