"""LangGraph orchestration: Planner → fan-out Researchers → Synthesizer → Critic loop."""
from __future__ import annotations

from datetime import datetime
from typing import Literal

from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.types import Send

from app.agents import (
    critic_node,
    planner_node,
    researcher_node,
    should_continue,
    synthesizer_node,
)
from app.config import MAX_PARALLEL
from app.state import AgentState


def _ready_tasks(state: AgentState) -> list:
    done_ids = {f["task_id"] for f in state.get("findings", [])}
    ready = []
    for t in state.get("plan", []):
        if t["id"] in done_ids:
            continue
        if all(dep in done_ids for dep in t.get("dependencies", [])):
            ready.append(t)
    return ready


def fan_out_or_synthesize(state: AgentState):
    """After planner (or replan), dispatch parallel researchers, or skip to synthesis."""
    ready = _ready_tasks(state)
    if not ready:
        return "synthesizer"
    batch = ready[:MAX_PARALLEL]
    return [
        Send(
            "researcher",
            {
                "task": t,
                "user_query": state["user_query"],
                "session_id": state.get("session_id", ""),
            },
        )
        for t in batch
    ]


def after_researcher(state: AgentState) -> Literal["fan_out", "synthesizer"]:
    """Send another researcher batch if there are pending tasks; else synthesize."""
    return "fan_out" if _ready_tasks(state) else "synthesizer"


def after_critic(state: AgentState) -> Literal["replan", "finalize"]:
    decision = should_continue(state)
    return "replan" if decision == "replan" else "finalize"


def replan_node(state: AgentState) -> dict:
    """Re-run planner with the latest critique as feedback."""
    return planner_node(state)


def finalize_node(state: AgentState) -> dict:
    iters = state.get("current_iteration", 1)
    tool_calls = state.get("total_tool_calls", 0)
    started = state.get("started_at")
    duration = ""
    if isinstance(started, datetime):
        duration = f" • duration={(datetime.now() - started).total_seconds():.1f}s"
    footer = (
        f"\n\n---\n*Generated by autonomous-researcher · iterations={iters} · "
        f"tool_calls={tool_calls}{duration}*"
    )
    final = (state.get("draft_report", "") or "") + footer
    return {"final_report": final}


def build_graph(checkpointer=None):
    g = StateGraph(AgentState)

    g.add_node("planner", planner_node)
    g.add_node("researcher", researcher_node)
    g.add_node("synthesizer", synthesizer_node)
    g.add_node("critic", critic_node)
    g.add_node("replan", replan_node)
    g.add_node("finalize", finalize_node)

    g.add_edge(START, "planner")

    g.add_conditional_edges(
        "planner",
        fan_out_or_synthesize,
        ["researcher", "synthesizer"],
    )
    g.add_conditional_edges(
        "replan",
        fan_out_or_synthesize,
        ["researcher", "synthesizer"],
    )

    g.add_conditional_edges(
        "researcher",
        after_researcher,
        {"fan_out": "researcher", "synthesizer": "synthesizer"},
    )

    g.add_edge("synthesizer", "critic")

    g.add_conditional_edges(
        "critic",
        after_critic,
        {"replan": "replan", "finalize": "finalize"},
    )

    g.add_edge("finalize", END)

    if checkpointer is None:
        checkpointer = MemorySaver()
    return g.compile(checkpointer=checkpointer)


_graph = None


def get_graph(checkpointer=None):
    global _graph
    if _graph is None:
        _graph = build_graph(checkpointer=checkpointer)
    return _graph


def reset_graph() -> None:
    global _graph
    _graph = None
